In [1]:
import pandas as pd
import numpy as np
import urllib.parse as parse

In [2]:
df = pd.read_csv('dataset/req2log.csv',index_col=0)
cols = df.columns
df = df.drop(index=0,axis=0)
df = df.reset_index(drop=True)

In [3]:
req_len = df.loc[:,"Method:":"HTTP_ver:"]

In [4]:
req_len

Method:                                              Path: HTTP_ver:
0         GET            http://localhost:8080/tienda1/index.jsp  HTTP/1.1
1         GET  http://localhost:8080/tienda1/publico/anadir.j...  HTTP/1.1
2        POST   http://localhost:8080/tienda1/publico/anadir.jsp  HTTP/1.1
3         GET  http://localhost:8080/tienda1/publico/autentic...  HTTP/1.1
4        POST  http://localhost:8080/tienda1/publico/autentic...  HTTP/1.1
...       ...                                                ...       ...
35994     GET       http://localhost:8080/tienda1/imagenes/1.gif  HTTP/1.1
35995     GET       http://localhost:8080/tienda1/imagenes/2.gif  HTTP/1.1
35996     GET       http://localhost:8080/tienda1/imagenes/3.gif  HTTP/1.1
35997     GET  http://localhost:8080/tienda1/imagenes/cmenbul...  HTTP/1.1
35998     GET    http://localhost:8080/tienda1/imagenes/logo.gif  HTTP/1.1

[35999 rows x 3 columns]

In [5]:
req__len = np.zeros((req_len.shape[0],1))
req__len.shape

(35999, 1)

In [6]:
from tqdm.notebook import tqdm
for i,d in tqdm(enumerate(req_len.itertuples(index=False))):
    leng =0
    for o in d:
        leng +=len(repr(o))
    req__len[i]=leng

0it [00:00, ?it/s]

In [7]:
print(req__len)

[[ 56.]
 [134.]
 [ 66.]
 ...
 [ 61.]
 [ 67.]
 [ 64.]]


In [8]:
arg_len = df.loc[:,["Path:","Arg:"]]

In [9]:
arg_len

Path:  \
0                http://localhost:8080/tienda1/index.jsp   
1      http://localhost:8080/tienda1/publico/anadir.j...   
2       http://localhost:8080/tienda1/publico/anadir.jsp   
3      http://localhost:8080/tienda1/publico/autentic...   
4      http://localhost:8080/tienda1/publico/autentic...   
...                                                  ...   
35994       http://localhost:8080/tienda1/imagenes/1.gif   
35995       http://localhost:8080/tienda1/imagenes/2.gif   
35996       http://localhost:8080/tienda1/imagenes/3.gif   
35997  http://localhost:8080/tienda1/imagenes/cmenbul...   
35998    http://localhost:8080/tienda1/imagenes/logo.gif   

                                                    Arg:  
0                                                    NaN  
1                                                    NaN  
2      id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...  
3                                                    NaN  
4      modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...  
...                                                  ...  
35994                                                NaN  
35995                                                NaN  
35996                                                NaN  
35997                                                NaN  
35998                                                NaN  

[35999 rows x 2 columns]

In [20]:
arg__len = np.zeros((arg_len.shape[0]))
import math
for i,d in enumerate(arg_len.itertuples(index=False)):
    try:
        if math.isnan(d[1]):
            try:
                arg = d[0].split('?')
                # print(d)
                arg = arg[1]        
            except IndexError:
                arg = ''
    except:
        arg=d[1]
    # print(arg)
    # print(len(repr(arg)))
    # break
    arg__len[i]= len(repr(arg))

In [21]:
arg__len = arg__len-2

array([ 3., 70., 70., ...,  3.,  3.,  3.])

In [12]:
# import math
# arg_ = []
# for i,d in enumerate(arg_len.itertuples(index=False)):
#     try:
#         if math.isnan(d[1]):
#             try:
#                 arg = d[0].split('?')
#                 # print(d)
#                 arg = arg[1]        
#             except IndexError:
#                 arg = ''
#     except:
#         arg=d[1]
#     arg_.append(arg)

In [13]:
# df2 = pd.DataFrame(arg_,index=None,columns=['Arg:'])

In [14]:
# df2

Arg:
0                                                       
1      id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...
2      id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...
3      modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...
4      modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...
...                                                  ...
35994                                                   
35995                                                   
35996                                                   
35997                                                   
35998                                                   

[35999 rows x 1 columns]

In [15]:
# df = df.drop(columns=["Arg:"],axis=1)

In [16]:
# df3 = pd.concat([df,df2 ],ignore_index=True,axis=1)
# df3.columns=cols

In [24]:
# df3 = df3.replace(r'^\s*$', np.nan, regex=True)

In [26]:
# df3.to_csv('dataset/req2log2.csv')

In [29]:
df3 = pd.read_csv('dataset/req2log2.csv',index_col=0)

In [30]:
df3

Method:                                              Path: HTTP_ver:  \
0         GET            http://localhost:8080/tienda1/index.jsp  HTTP/1.1   
1         GET  http://localhost:8080/tienda1/publico/anadir.j...  HTTP/1.1   
2        POST   http://localhost:8080/tienda1/publico/anadir.jsp  HTTP/1.1   
3         GET  http://localhost:8080/tienda1/publico/autentic...  HTTP/1.1   
4        POST  http://localhost:8080/tienda1/publico/autentic...  HTTP/1.1   
...       ...                                                ...       ...   
35994     GET       http://localhost:8080/tienda1/imagenes/1.gif  HTTP/1.1   
35995     GET       http://localhost:8080/tienda1/imagenes/2.gif  HTTP/1.1   
35996     GET       http://localhost:8080/tienda1/imagenes/3.gif  HTTP/1.1   
35997     GET  http://localhost:8080/tienda1/imagenes/cmenbul...  HTTP/1.1   
35998     GET    http://localhost:8080/tienda1/imagenes/logo.gif  HTTP/1.1   

       Request:                                        User-Agent:   Pragma:  \
0           NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
1           NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
2           NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
3           NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
4           NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
...         ...                                                ...       ...   
35994       NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
35995       NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
35996       NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
35997       NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   
35998       NaN  Mozilla/5.0, (compatible;, Konqueror/3.5;, Lin...  no-cache   

      Cache-control:                                            Accept:  \
0           no-cache  text/xml,application/xml,application/xhtml+xml...   
1           no-cache  text/xml,application/xml,application/xhtml+xml...   
2           no-cache  text/xml,application/xml,application/xhtml+xml...   
3           no-cache  text/xml,application/xml,application/xhtml+xml...   
4           no-cache  text/xml,application/xml,application/xhtml+xml...   
...              ...                                                ...   
35994       no-cache  text/xml,application/xml,application/xhtml+xml...   
35995       no-cache  text/xml,application/xml,application/xhtml+xml...   
35996       no-cache  text/xml,application/xml,application/xhtml+xml...   
35997       no-cache  text/xml,application/xml,application/xhtml+xml...   
35998       no-cache  text/xml,application/xml,application/xhtml+xml...   

                          Accept-Encoding:                Accept-Charset:  \
0      x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
1      x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
2      x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
3      x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
4      x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
...                                    ...                            ...   
35994  x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
35995  x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
35996  x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
35997  x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   
35998  x-gzip,, x-deflate,, gzip,, deflate  utf-8,, utf-8;q=0.5,, *;q=0.5   

      Accept-Language:           Host:  \
0                   en  localhost:8080   
1                   en  localhost:8080   
2                   en  localhost:8080   
3                   en  localhost:8080   
4                   en  localhost:8080   
...                ...        

In [37]:
#######################################     Number of Argument      #############################

num_arg= np.zeros(df3.shape[0])

for i,d in enumerate(df3["Arg:"]):
    num=0
    # print(d)
    try:
        if math.isnan(d):
            num=0
    except:
        num = d.count('=')
    num_arg[i]=num
    # print(num)
    # if i ==10: break

In [47]:
###################################     Path of Length      ###################################

path_len = np.zeros(df3.shape[0])

for i, d in enumerate(df3["Path:"]):
    l = 0
    l = len(d)
    # print(l)
    # break
    path_len[i]=l

In [51]:
################################        Special Char Number     #############################
import re
spchar_num = np.zeros((df3.shape[0]))
for i,d in enumerate(df3["Path:"]):
    match = re.findall("[^a-zA-Z0-9_]",d)
    # print(len(match))
    # break
    spchar_num[i]=len(match)


In [59]:
np.array([req__len.reshape(-1,),arg__len.reshape(-1,),num_arg.reshape(-1,),path_len.reshape(-1,),spchar_num.reshape(-1,)])

array([[ 56., 134.,  66., ...,  61.,  67.,  64.],
       [  3.,  70.,  70., ...,   3.,   3.,   3.],
       [  0.,   5.,   5., ...,   0.,   0.,   0.],
       [ 39., 117.,  48., ...,  44.,  50.,  47.],
       [  7.,  22.,   8., ...,   8.,   8.,   8.]])